defaults:
  - _self_
  # - task@_global_: distracting_finger_spin
  - task@_global_: kitchen_kitchen-light-v0
  - agent@_global_: sear
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 3
action_repeat: 2
# action_repeat: 1   ### For Franka
discount: 0.99
has_success_metric: false # Overidden in task yaml if true
noisy_mask_drop_prob: 0.0
slim_mask_cfg:
  use_slim_mask: false
  scale: 3
  threshold: 0.9
  sigma: 0.5

use_rgbm: false
# ted: true
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
save_buffer_snapshot: false
# replay buffer
replay_buffer_size: 250000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 45
device: cuda
save_video: true
save_train_video: false
use_tb: true
add_segmentation_to_obs: true # Overidden in agent yaml if needed by agent
# agent
lr: 1e-4
# lr: 1e-3
feature_dim: 50

distraction:
  difficulty: medium
  dataset_path: /home/pores/Projects/sear-rl/Dataset/DAVIS/JPEGImages/480p
  
use_wandb: true
wandb:
  project_name: "sear-rl"
  run_name: "distracting_cup_catch_sea21"

experiment_id: "Default_Experiment_ID"

# pretrain:
#   path: /home/amey/projects/sear-rl/exp_local/mask_without_ted/best.pt
#   just_encoder_decoders: false

hydra:
  run:
    dir: ./exp_local/distracting_cup_catch_sear212
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm